// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nakuynzcpxgvrpxqistm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ha3V5bnpjcHhndnJweHFpc3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDM1OTgsImV4cCI6MjA2MjIxOTU5OH0.GAy1PiqCaHDiHcawRQq0lQXTnnTV0LQFmFUIGw5uDzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);